# Generated by Django 4.2.7 on 2024-04-19 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_receiver', to=settings.AUTH_USER_MODEL, verbose_name='수신자')),
                ('send_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_sender', to=settings.AUTH_USER_MODEL, verbose_name='발신자')),
            ],
        ),
    ]
