# Generated by Django 4.2.7 on 2024-04-22 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_messageblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageblock',
            old_name='send_id',
            new_name='req_id',
        ),
        migrations.RenameField(
            model_name='messageblock',
            old_name='recv_id',
            new_name='tar_id',
        ),
    ]
