# Generated by Django 4.2.7 on 2024-05-12 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0015_postmemberbookmark'),
        ('message', '0004_remove_message_recv_id_remove_message_send_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_anonymous_num', models.IntegerField(null=True, verbose_name='최초발신자 익명 숫자')),
                ('receiver_anonymous_num', models.IntegerField(verbose_name='최초수신자 익명 숫자')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_post', to='board.post', verbose_name='쪽지 시작점 게시글')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_message_receiver', to=settings.AUTH_USER_MODEL, verbose_name='최초수신자')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_message_sender', to=settings.AUTH_USER_MODEL, verbose_name='최초발신자')),
            ],
        ),
    ]
