# Generated by Django 4.2.7 on 2024-05-16 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_postmemberbookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0006_remove_messageinfo_sender_anonymous_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_anonymous_num', models.IntegerField(verbose_name='최초수신자 익명 숫자')),
                ('first_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_message_receiver', to=settings.AUTH_USER_MODEL, verbose_name='최초수신자')),
                ('first_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_message_sender', to=settings.AUTH_USER_MODEL, verbose_name='최초발신자')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_post', to='board.post', verbose_name='쪽지 시작점 게시글')),
            ],
        ),
        migrations.DeleteModel(
            name='MessageInfo',
        ),
        migrations.AddField(
            model_name='message',
            name='message_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_room', to='message.messageroom', verbose_name='쪽지방'),
        ),
    ]
