# Generated by Django 4.2.7 on 2024-05-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_messageroom_delete_messageinfo_message_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='post_title',
            field=models.CharField(default='', max_length=90, verbose_name='쪽지 시작점 게시글 제목'),
        ),
    ]
