# Generated by Django 4.2.7 on 2024-05-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_messageroom_board'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
        migrations.AlterModelTable(
            name='messageroom',
            table='message_room',
        ),
    ]
