# Generated by Django 4.2.7 on 2024-05-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_alter_message_table_alter_messageroom_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='messageblock',
            table='message_block',
        ),
    ]
