# Generated by Django 4.2.7 on 2024-08-17 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0011_alter_messageblock_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(default='', validators=[django.core.validators.MinLengthValidator(1)], verbose_name='내용'),
        ),
    ]
