# Generated by Django 4.2.7 on 2024-02-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_report_comment_alter_report_post'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='report',
            table='report',
        ),
    ]
