# Generated by Django 4.2.7 on 2024-02-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_report_comment_alter_report_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('WAITING', 'waiting'), ('PENDING', 'pending'), ('VALID', 'valid'), ('INVALID', 'invalid')], default='WAITING', max_length=10),
        ),
    ]
