# Generated by Django 4.2.7 on 2024-03-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('WAITING', '검사 대기'), ('PENDING', '관리자 확인 대기'), ('VALID', '유효한 신고'), ('INVALID', '유효하지 않은 신고')], default='WAITING', max_length=10),
        ),
    ]
