# Generated by Django 4.2.7 on 2024-07-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_report_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='member',
        ),
        migrations.AddField(
            model_name='report',
            name='is_member_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
