# Generated by Django 4.2.7 on 2024-07-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_remove_report_is_member_blocked_report_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='member_status',
            field=models.IntegerField(choices=[(0, '정지하지 않음'), (3, '3일 정지'), (7, '7일 정지'), (30, '30일 정지')], default=0),
        ),
    ]
