# Generated by Django 4.2.7 on 2024-09-02 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0004_alter_dorm_dorm_name'),
        ('report', '0011_alter_report_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='dorm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.dorm', verbose_name='기숙사'),
        ),
    ]
