# Generated by Django 4.2.7 on 2024-09-02 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0004_alter_dorm_dorm_name'),
        ('report', '0012_report_dorm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='dorm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.dorm', verbose_name='피신고글 기숙사'),
        ),
    ]
