# Generated by Django 4.2.7 on 2024-02-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormitoryPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dormitory_code', models.CharField(max_length=7)),
                ('room_number', models.CharField(max_length=8)),
                ('phone_number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dormitory_personal_info',
            },
        ),
    ]
