# Generated by Django 4.2.7 on 2024-02-15 23:10

from django.db import migrations, models
import member.domains.personal_info_excel_file


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_dormitorypersonalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfoExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to=member.domains.personal_info_excel_file.path_and_rename)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'personal_info_excel_file',
            },
        ),
    ]
