# Generated by Django 4.2.7 on 2024-02-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_personalinfoexcelfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='email',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='member',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='dormitory_card',
        ),
        migrations.RemoveField(
            model_name='member',
            name='dormitory_code',
        ),
        migrations.RemoveField(
            model_name='member',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '활동'), ('BANNED', '정지'), ('WITHDRAWAL', '탈퇴')], default='ACTIVE', max_length=255),
        ),
    ]
