# Generated by Django 4.2.7 on 2024-09-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_alter_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dormitory_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
