# Generated by Django 4.2.7 on 2024-09-10 07:28

from django.db import migrations, models

def update_member_table(apps, schema_editor):
    Member = apps.get_model('member', 'Member')
    for member in Member.objects.all():
        if member.dormitory_code == None:
            member.dormitory_code = member.username
            member.username = f"{member.dorm.pk}-{member.dormitory_code}"
            member.save()


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_alter_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dormitory_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(update_member_table)
    ]
