# Generated by Django 4.2.7 on 2023-11-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.CharField(default='', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=100)),
                ('content', models.TextField(default='')),
                ('images', models.URLField(default='')),
            ],
        ),
    ]
