# Generated by Django 4.2.7 on 2023-11-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticelist',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
