# Generated by Django 4.2.7 on 2023-11-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_noticelist_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticelist',
            name='images',
            field=models.TextField(null=True),
        ),
    ]
