# Generated by Django 4.2.7 on 2024-02-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_alter_noticelist_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticelist',
            name='notice_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
