# Generated by Django 4.2.7 on 2024-09-01 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0004_alter_dorm_dorm_name'),
        ('notice', '0004_noticelist_notice_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticelist',
            name='dorm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.dorm'),
        ),
    ]
