# Generated by Django 4.2.7 on 2023-11-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_token', models.CharField(max_length=255)),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
    ]
