# Generated by Django 4.2.7 on 2024-02-11 12:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('push', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='last_logged_in_at',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('device_token', 'member')},
        ),
        migrations.RemoveField(
            model_name='device',
            name='is_valid',
        ),
    ]
