# Generated by Django 4.2.7 on 2024-02-11 11:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('push', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('device_token', 'member')},
        ),
    ]
