# Generated by Django 4.2.7 on 2024-03-11 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('push', '0003_adminpushnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('breakfast', models.BooleanField(default=True)),
                ('lunch', models.BooleanField(default=True)),
                ('dinner', models.BooleanField(default=True)),
                ('lightning_post', models.BooleanField(default=True)),
                ('comment', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_detail',
            },
        ),
    ]
