# Generated by Django 4.2.7 on 2024-03-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0004_notificationdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationDetail',
        ),
    ]
