# Generated by Django 4.2.7 on 2024-05-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0006_notificationdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdetail',
            name='lost_item',
            field=models.BooleanField(default=True),
        ),
    ]
