# Generated by Django 4.2.7 on 2023-11-28 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "date_code",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("date_detail", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Lunch",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=512)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lunches",
                        to="menu.menu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dinner",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=512)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dinners",
                        to="menu.menu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Breakfast",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=512)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breakfasts",
                        to="menu.menu",
                    ),
                ),
            ],
        ),
    ]
