# Generated by Django 4.2.7 on 2023-11-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_code", models.CharField(max_length=6)),
                ("date_detail", models.CharField(max_length=15)),
                ("breakfast", models.CharField(max_length=1000)),
                ("lunch", models.CharField(max_length=1000)),
                ("dinner", models.CharField(max_length=1000)),
            ],
        ),
    ]
