# Generated by Django 4.2.7 on 2024-03-03 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast', to='menu.menu'),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner', to='menu.menu'),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='menu.menu'),
        ),
    ]
