# Generated by Django 4.2.7 on 2023-11-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="breakfast",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="menu",
            name="dinner",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="menu",
            name="lunch",
            field=models.CharField(max_length=512),
        ),
    ]
