# Generated by Django 4.2.7 on 2023-11-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_menu_breakfast_alter_menu_dinner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="breakfast",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="dinner",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="lunch",
        ),
        migrations.CreateModel(
            name="Lunch",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("menu", models.CharField(max_length=512)),
                (
                    "date_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menu.menu"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dinner",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("menu", models.CharField(max_length=512)),
                (
                    "date_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menu.menu"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Breakfast",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("menu", models.CharField(max_length=512)),
                (
                    "date_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menu.menu"
                    ),
                ),
            ],
        ),
    ]
