# Generated by Django 4.2.7 on 2024-09-01 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0004_alter_dorm_dorm_name'),
        ('menu', '0002_alter_breakfast_menu_alter_dinner_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast',
            name='dorm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.dorm'),
        ),
        migrations.AddField(
            model_name='dinner',
            name='dorm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.dorm'),
        ),
        migrations.AddField(
            model_name='lunch',
            name='dorm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.dorm'),
        ),
        migrations.AddField(
            model_name='menu',
            name='dorm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.dorm'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('date_code', 'dorm')},
        ),
    ]
