# Generated by Django 4.2.7 on 2023-11-28 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_remove_menu_breakfast_remove_menu_dinner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breakfast",
            name="date_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breakfasts",
                to="menu.menu",
            ),
        ),
        migrations.AlterField(
            model_name="dinner",
            name="date_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dinners",
                to="menu.menu",
            ),
        ),
        migrations.AlterField(
            model_name="lunch",
            name="date_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lunches",
                to="menu.menu",
            ),
        ),
    ]
