# Generated by Django 4.2.7 on 2024-07-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorm_name', models.CharField(max_length=60, verbose_name='기숙사 이름')),
            ],
            options={
                'db_table': 'dorm',
            },
        ),
    ]
