# Generated by Django 4.2.7 on 2024-07-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='descriptions',
            field=models.TextField(default='', verbose_name='비고'),
        ),
    ]
