# Generated by Django 4.2.7 on 2024-07-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0002_dorm_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='descriptions',
            field=models.CharField(default='', max_length=900, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='dorm_name',
            field=models.CharField(choices=[('ALL', '전체 기숙사'), ('EAST', '동서울관'), ('WEST', '서서울관')], max_length=60, unique=True, verbose_name='기숙사 이름'),
        ),
    ]
