# Generated by Django 4.2.7 on 2024-07-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0003_alter_dorm_descriptions_alter_dorm_dorm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='dorm_name',
            field=models.CharField(choices=[('ALL', '전체 기숙사'), ('EAST', '동서울관'), ('WEST', '서서울관')], max_length=255, unique=True, verbose_name='기숙사 이름'),
        ),
    ]
