# Generated by Django 4.2.7 on 2024-02-10 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_parent_comment_parent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='postimage',
            name='is_thumbnail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='board.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
    ]
