# Generated by Django 4.2.7 on 2024-02-11 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_postimage_is_deleted_postimage_is_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='member',
            new_name='member_id',
        ),
    ]
