# Generated by Django 4.2.7 on 2024-02-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_rename_member_comment_member_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='board_id',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='postimage',
            old_name='post_id',
            new_name='post',
        ),
    ]
