# Generated by Django 4.2.7 on 2024-02-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_rename_member_id_comment_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
