# Generated by Django 4.2.7 on 2024-02-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_board_table_alter_comment_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postimage',
            table='post_image',
        ),
    ]
