# Generated by Django 4.2.7 on 2024-02-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_postimage_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
