# Generated by Django 4.2.7 on 2024-03-17 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0011_comment_anonymous_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes_cnt',
            field=models.IntegerField(default=0, null=True, verbose_name='좋아요 수'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_cnt',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='PostMemberLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.post')),
            ],
            options={
                'db_table': 'post_member_like',
            },
        ),
        migrations.CreateModel(
            name='PopularPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_at', models.DateTimeField(auto_now_add=True, verbose_name='인기게시물 등록 시간')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.post')),
            ],
            options={
                'db_table': 'popular_post',
            },
        ),
        migrations.CreateModel(
            name='CommentMemberLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.comment')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment_member_like',
            },
        ),
    ]
