# Generated by Django 4.2.7 on 2024-02-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    table_name = "post"
    index_name1 = "title_fulltext_index"
    index_name2 = "body_fulltext_index"

    dependencies = [
        ('board', '0011_comment_anonymous_number'),
    ]

    operations = [
        migrations.RunSQL([
            f'CREATE FULLTEXT INDEX {index_name1} ON {table_name}(title) WITH PARSER ngram',
            f'CREATE FULLTEXT INDEX {index_name2} ON {table_name}(body) WITH PARSER ngram',
            f'DROP INDEX {index_name1} on {table_name}',
            f'DROP INDEX {index_name2} on {table_name}',
        ]
        ),
    ]


