# Generated by Django 4.2.7 on 2024-03-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_comment_likes_cnt_post_likes_cnt_postmemberlike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes_cnt',
            field=models.IntegerField(default=0, verbose_name='좋아요 수'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes_cnt',
            field=models.IntegerField(default=0, verbose_name='좋아요 수'),
        ),
    ]
