# Generated by Django 4.2.7 on 2024-03-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_alter_comment_likes_cnt_alter_post_likes_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmark_cnt',
            field=models.IntegerField(default=0, verbose_name='스크랩 수'),
        ),
    ]
