# Generated by Django 4.2.7 on 2024-07-29 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0004_alter_dorm_dorm_name'),
        ('board', '0015_postmemberbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dorm',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='dorm.dorm', verbose_name='기숙사'),
        ),
        migrations.AddField(
            model_name='post',
            name='dorm',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='dorm.dorm', verbose_name='기숙사'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='dorm',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='post_image', to='dorm.dorm', verbose_name='기숙사'),
        ),
    ]
