# Generated by Django 4.2.7 on 2024-09-01 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0004_alter_dorm_dorm_name'),
        ('board', '0016_comment_dorm_post_dorm_postimage_dorm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dorm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='dorm.dorm', verbose_name='기숙사'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dorm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='dorm.dorm', verbose_name='기숙사'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='dorm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_image', to='dorm.dorm', verbose_name='기숙사'),
        ),
    ]
